/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cordys_coe_jni_PSBridge */

#ifndef _Included_com_cordys_coe_jni_PSBridge
#define _Included_com_cordys_coe_jni_PSBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cordys_coe_jni_PSBridge
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cordys_coe_jni_PSBridge_execute
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_cordys_coe_jni_PSBridge
 * Method:    addSnapIn
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cordys_coe_jni_PSBridge_addSnapIn
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
